version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: daniel-db
    environment:
      MYSQL_DATABASE: daniel
      MYSQL_USER: daniel_user
      MYSQL_PASSWORD: daniel1234
      MYSQL_ROOT_PASSWORD: daniel1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "daniel_user", "--password=daniel1234" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2GB

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/daniel?allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
      JAVA_OPTS: "-Xms256m -Xmx512m"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: