spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: group-random
#  mvc:
#    static-path-pattern: /static/**
  messages:
    basename: errors
  sql:
    init:
      mode: never
      platform: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 50
    defer-datasource-initialization: true

server:
  tomcat:
    connection-timeout: 60000
  servlet:
    session:
      timeout: 180m
