spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: group-random
#  mvc:
#    static-path-pattern: /static/**
  messages:
    basename: errors
  sql:
    init:
      mode: never
      platform: mysql
  datasource:
    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQL_DATABASE:daniel}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: ${MYSQLUSER:daniel_user}
    password: ${MYSQLPASSWORD:daniel1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # 추가
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 50
    defer-datasource-initialization: true

server:
  tomcat:
    connection-timeout: 60000
  servlet:
    session:
      timeout: 180m
admin:
  username: ${ADMIN_USERNAME:daniel}
  password: ${ADMIN_PASSWORD}